spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WhitelephantDesginer/ConfigServer.git
          clone-on-start: true
server:
  port: ${PORT:8888}
